### ISSUE TITLE
activation of the release step

### ISSUE THREAD

**Issue by yanns** [EECOLOR/sbt-release-custom-steps#1]
I tried to integrate your step as described in the README, by just adding it into the build.sbt.
But it does not do anything.

Are you sure we do not have to add your step into the release process, like described here: https://github.com/sbt/sbt-release#the-default-release-process

**Comment by EECOLOR** [comment]
Yes, of course. I should have added that to the documentation.

**Comment by yanns** [comment]
Actually, I saw that your actual documentation is sufficient.

**Comment by EECOLOR** [comment]
As long as you add it as the last statement it indeed is.
